Feature/add service
ohlunlacassi/hotel-tishjama pull request #9
Opened 2023-09-22 08:48 UTC by ohlunlacassi

2023-09-22 14:53 UTC, ahohnsen requested changes
Nice! 🙌🏼 Have a look at my comments 🙂

2023-09-22 14:53 UTC, ahohnsen commented on components/ServiceForm/index.js
> +export default function ServiceForm({ onSubmit, formName }) {
It seems like you do not pass any `formName` from `/pages/create.js` to the `ServiceForm`. Therefore I suggest to delete `formName` here. 
```suggestion
export default function ServiceForm({ onSubmit }) {
```

2023-09-22 14:53 UTC, ahohnsen commented on components/ServiceForm/index.js
> +      <form onSubmit={handleAdd} aria-labelledby={formName}>
You can use here `aria-label` instead of `aria-labelledby`, so you do not need `formName`.

2023-09-22 14:53 UTC, ahohnsen commented on components/ServiceForm/index.js
> +        </p>
I would suggest to eliminate the `p` elements as they do not seem to serve any purpose here. 🧹 
```suggestion
          <label htmlFor="name">service Name: </label>
          <input id="name" name="name" type="text" required></input>
          <label htmlFor="image">Image: </label>
          <input id="image" name="image" type="text" required></input>
          <label htmlFor="description">Description: </label>
          <textarea
            id="description"
            name="description"
            cols="20"
            rows="4"
            required
          ></textarea>
          <label htmlFor="date">Date: </label>
          <input id="date" name="date" type="date" required></input>
          <label htmlFor="time">Time: </label>
          <input id="time" name="time" type="time" required></input>
          <label htmlFor="price">Price: </label>
          <input id="price" name="price" type="number" required></input>
          <span> EUR</span>
```

2023-09-22 14:53 UTC, ahohnsen commented on components/ServiceList/index.js
> +      </div>
You probably do not need the `div` element here.
```suggestion
        <Link href="/create">+ add service</Link>
```

2023-09-22 14:53 UTC, ahohnsen commented on pages/create.js
> +    mutate(`api/services`);
I believe that you can omit the use of `mutate` in this context, as you are redirecting to the homepage where the data will be automatically re-validated.🤔 
```suggestion
```

2023-09-22 14:53 UTC, ahohnsen commented on pages/create.js
> +import { mutate } from "swr";
See below

```suggestion
```

2023-09-22 14:53 UTC, ahohnsen commented on pages/create.js
> +      </div>
I suggest to delete the `div` element here, as it does not serve any purpose here. Additionally, you do not need a `p` element inside the `Link` component. You can simply write the content of the `Link` inbetween the opening and closing tag.
```suggestion

        <Link href="/">
         cancel
        </Link>

```

2023-09-22 14:53 UTC, ahohnsen commented on components/ServiceForm/index.js
> +          <input id="name" name="name" type="text" required></input>
```suggestion
          <input id="name" name="name" type="text" required />
```

2023-09-25 08:37 UTC, JessicaLoers approved these changes
I see you have adopted all the proposed changes.
**Well done ✨**

2023-09-25 09:29 UTC, merged